targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
